all:
	g++ -std=gnu++14 -o a sol.cpp

.PHONY: a
a:
	g++ -std=gnu++14 -o a a.cpp

.PHONY: b
b:
	g++ -std=gnu++14 -o a b.cpp

.PHONY: c
c:
	g++ -std=gnu++14 -o a c.cpp

.PHONY: d
d:
	g++ -std=gnu++14 -o a d.cpp

.PHONY: e
e:
	g++ -std=gnu++14 -o a e.cpp

.PHONY: f
f:
	g++ -std=gnu++14 -o a f.cpp

init:
	@mv a.cpp abak.cpp
	@mv b.cpp bbak.cpp
	@mv c.cpp cbak.cpp
	@mv d.cpp dbak.cpp
	@mv e.cpp ebak.cpp
	@mv f.cpp fbak.cpp
	@cp tmp.cpp a.cpp 
	@cp tmp.cpp b.cpp 
	@cp tmp.cpp c.cpp 
	@cp tmp.cpp d.cpp 
	@cp tmp.cpp e.cpp 
	@cp tmp.cpp f.cpp 
