all:
	@python3 sol.py

.PHONY: a
a:
	@python3 a.py
.PHONY: b
b:
	@python3 b.py
.PHONY: c
c:
	@python3 c.py
.PHONY: d
d:
	@python3 d.py
.PHONY: e
e:
	@python3 e.py
.PHONY: f
f:
	@python3 f.py
.PHONY: init
init:
	./init
